before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libcairo2-dev libjpeg-dev libgif-dev npm nodejs libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

language: node_js
node_js:
  - '0.12'
